# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Installieren von Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Installieren der Packete
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Starten des Monitor Skripts
      run: python MonitorRealtime.py -r 1
    - name: Unittest
      run: python Test_Monitor.py
